/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BindDecimalOptions, BindOptions, MaskPattern } from "../../dist/mother-mask.d.mts";
export { BindDecimalOptions, BindOptions, MaskPattern } from "../../dist/mother-mask.d.mts";
export namespace Components {
    /**
     * `<stencil-mask-decimal>` — a Stencil custom element wrapping `bindDecimal`
     * from `mother-mask`. Same lifecycle contract as {@link StencilMaskInput }:
     * ref grabbed in `render()`, bound in `connectedCallback`/`componentDidLoad`
     * (browser-only either way), disposed in `disconnectedCallback`, reactive
     * rebind via `@Watch`. Emits `value-change` (`detail: string`) and
     * `numeric-value-change` (`detail: number`).
     */
    interface StencilMaskDecimal {
        /**
          * @default false
         */
        "disabled": boolean;
        "name"?: string;
        "options"?: Omit<BindDecimalOptions, 'onChange'>;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    /**
     * `<stencil-mask-input>` — a Stencil custom element wrapping `bind` from
     * `mother-mask`.
     * The native `<input>` ref is grabbed via `render()`'s `ref` callback (the
     * only point Stencil hands back a real DOM node). Binding then happens in
     * `connectedCallback` when that ref is already available — true on every
     * *re*-connection (the element was moved or re-appended) — and otherwise in
     * `componentDidLoad`, which fires exactly once after the very first render,
     * once the ref exists for the first time. Either way, the browser is the
     * only place these run; Stencil's SSR/hydration path never calls them.
     * `disconnectedCallback` always disposes, and `@Watch` reactively rebinds
     * whenever `mask`/`options`/`value` change.
     * ```html
     * <stencil-mask-input mask="999-999"></stencil-mask-input>
     * ```
     */
    interface StencilMaskInput {
        /**
          * @default false
         */
        "disabled": boolean;
        "inputModeAttr"?: string;
        "mask": MaskPattern;
        "name"?: string;
        "options"?: Omit<BindOptions, 'onChange'>;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface StencilMaskDecimalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStencilMaskDecimalElement;
}
export interface StencilMaskInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStencilMaskInputElement;
}
declare global {
    interface HTMLStencilMaskDecimalElementEventMap {
        "value-change": string;
        "numeric-value-change": number;
    }
    /**
     * `<stencil-mask-decimal>` — a Stencil custom element wrapping `bindDecimal`
     * from `mother-mask`. Same lifecycle contract as {@link StencilMaskInput }:
     * ref grabbed in `render()`, bound in `connectedCallback`/`componentDidLoad`
     * (browser-only either way), disposed in `disconnectedCallback`, reactive
     * rebind via `@Watch`. Emits `value-change` (`detail: string`) and
     * `numeric-value-change` (`detail: number`).
     */
    interface HTMLStencilMaskDecimalElement extends Components.StencilMaskDecimal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStencilMaskDecimalElementEventMap>(type: K, listener: (this: HTMLStencilMaskDecimalElement, ev: StencilMaskDecimalCustomEvent<HTMLStencilMaskDecimalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStencilMaskDecimalElementEventMap>(type: K, listener: (this: HTMLStencilMaskDecimalElement, ev: StencilMaskDecimalCustomEvent<HTMLStencilMaskDecimalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStencilMaskDecimalElement: {
        prototype: HTMLStencilMaskDecimalElement;
        new (): HTMLStencilMaskDecimalElement;
    };
    interface HTMLStencilMaskInputElementEventMap {
        "value-change": string;
    }
    /**
     * `<stencil-mask-input>` — a Stencil custom element wrapping `bind` from
     * `mother-mask`.
     * The native `<input>` ref is grabbed via `render()`'s `ref` callback (the
     * only point Stencil hands back a real DOM node). Binding then happens in
     * `connectedCallback` when that ref is already available — true on every
     * *re*-connection (the element was moved or re-appended) — and otherwise in
     * `componentDidLoad`, which fires exactly once after the very first render,
     * once the ref exists for the first time. Either way, the browser is the
     * only place these run; Stencil's SSR/hydration path never calls them.
     * `disconnectedCallback` always disposes, and `@Watch` reactively rebinds
     * whenever `mask`/`options`/`value` change.
     * ```html
     * <stencil-mask-input mask="999-999"></stencil-mask-input>
     * ```
     */
    interface HTMLStencilMaskInputElement extends Components.StencilMaskInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStencilMaskInputElementEventMap>(type: K, listener: (this: HTMLStencilMaskInputElement, ev: StencilMaskInputCustomEvent<HTMLStencilMaskInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStencilMaskInputElementEventMap>(type: K, listener: (this: HTMLStencilMaskInputElement, ev: StencilMaskInputCustomEvent<HTMLStencilMaskInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStencilMaskInputElement: {
        prototype: HTMLStencilMaskInputElement;
        new (): HTMLStencilMaskInputElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-mask-decimal": HTMLStencilMaskDecimalElement;
        "stencil-mask-input": HTMLStencilMaskInputElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * `<stencil-mask-decimal>` — a Stencil custom element wrapping `bindDecimal`
     * from `mother-mask`. Same lifecycle contract as {@link StencilMaskInput }:
     * ref grabbed in `render()`, bound in `connectedCallback`/`componentDidLoad`
     * (browser-only either way), disposed in `disconnectedCallback`, reactive
     * rebind via `@Watch`. Emits `value-change` (`detail: string`) and
     * `numeric-value-change` (`detail: number`).
     */
    interface StencilMaskDecimal {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "name"?: string;
        "onNumeric-value-change"?: (event: StencilMaskDecimalCustomEvent<number>) => void;
        "onValue-change"?: (event: StencilMaskDecimalCustomEvent<string>) => void;
        "options"?: Omit<BindDecimalOptions, 'onChange'>;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    /**
     * `<stencil-mask-input>` — a Stencil custom element wrapping `bind` from
     * `mother-mask`.
     * The native `<input>` ref is grabbed via `render()`'s `ref` callback (the
     * only point Stencil hands back a real DOM node). Binding then happens in
     * `connectedCallback` when that ref is already available — true on every
     * *re*-connection (the element was moved or re-appended) — and otherwise in
     * `componentDidLoad`, which fires exactly once after the very first render,
     * once the ref exists for the first time. Either way, the browser is the
     * only place these run; Stencil's SSR/hydration path never calls them.
     * `disconnectedCallback` always disposes, and `@Watch` reactively rebinds
     * whenever `mask`/`options`/`value` change.
     * ```html
     * <stencil-mask-input mask="999-999"></stencil-mask-input>
     * ```
     */
    interface StencilMaskInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "inputModeAttr"?: string;
        "mask": MaskPattern;
        "name"?: string;
        "onValue-change"?: (event: StencilMaskInputCustomEvent<string>) => void;
        "options"?: Omit<BindOptions, 'onChange'>;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface StencilMaskDecimalAttributes {
        "value": string;
        "name": string;
        "placeholder": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
    }
    interface StencilMaskInputAttributes {
        "mask": MaskPattern;
        "value": string;
        "name": string;
        "placeholder": string;
        "inputModeAttr": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
    }

    interface IntrinsicElements {
        "stencil-mask-decimal": Omit<StencilMaskDecimal, keyof StencilMaskDecimalAttributes> & { [K in keyof StencilMaskDecimal & keyof StencilMaskDecimalAttributes]?: StencilMaskDecimal[K] } & { [K in keyof StencilMaskDecimal & keyof StencilMaskDecimalAttributes as `attr:${K}`]?: StencilMaskDecimalAttributes[K] } & { [K in keyof StencilMaskDecimal & keyof StencilMaskDecimalAttributes as `prop:${K}`]?: StencilMaskDecimal[K] };
        "stencil-mask-input": Omit<StencilMaskInput, keyof StencilMaskInputAttributes> & { [K in keyof StencilMaskInput & keyof StencilMaskInputAttributes]?: StencilMaskInput[K] } & { [K in keyof StencilMaskInput & keyof StencilMaskInputAttributes as `attr:${K}`]?: StencilMaskInputAttributes[K] } & { [K in keyof StencilMaskInput & keyof StencilMaskInputAttributes as `prop:${K}`]?: StencilMaskInput[K] } & OneOf<"mask", StencilMaskInput["mask"], StencilMaskInputAttributes["mask"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * `<stencil-mask-decimal>` — a Stencil custom element wrapping `bindDecimal`
             * from `mother-mask`. Same lifecycle contract as {@link StencilMaskInput }:
             * ref grabbed in `render()`, bound in `connectedCallback`/`componentDidLoad`
             * (browser-only either way), disposed in `disconnectedCallback`, reactive
             * rebind via `@Watch`. Emits `value-change` (`detail: string`) and
             * `numeric-value-change` (`detail: number`).
             */
            "stencil-mask-decimal": LocalJSX.IntrinsicElements["stencil-mask-decimal"] & JSXBase.HTMLAttributes<HTMLStencilMaskDecimalElement>;
            /**
             * `<stencil-mask-input>` — a Stencil custom element wrapping `bind` from
             * `mother-mask`.
             * The native `<input>` ref is grabbed via `render()`'s `ref` callback (the
             * only point Stencil hands back a real DOM node). Binding then happens in
             * `connectedCallback` when that ref is already available — true on every
             * *re*-connection (the element was moved or re-appended) — and otherwise in
             * `componentDidLoad`, which fires exactly once after the very first render,
             * once the ref exists for the first time. Either way, the browser is the
             * only place these run; Stencil's SSR/hydration path never calls them.
             * `disconnectedCallback` always disposes, and `@Watch` reactively rebinds
             * whenever `mask`/`options`/`value` change.
             * ```html
             * <stencil-mask-input mask="999-999"></stencil-mask-input>
             * ```
             */
            "stencil-mask-input": LocalJSX.IntrinsicElements["stencil-mask-input"] & JSXBase.HTMLAttributes<HTMLStencilMaskInputElement>;
        }
    }
}
