/**
 * Writes `src/generated/snippets/index.ts` (every sample in
 * src/content/snippets.ts, tokenized) and one `src/generated/snippets/<adapter>.ts`
 * per framework adapter (the same samples adapted to that framework's API).
 *
 * Highlighting is a build-time step on purpose. Shiki's grammars and WASM
 * regex engine are far larger than the whole site, and the tokens for a given
 * snippet never change at runtime — so the browser gets a small array of
 * `[text, className]` pairs and renders them with ordinary spans. That keeps
 * the server-rendered markup and the SPA-rendered markup byte-identical, which
 * is what lets `hydrate()` claim the SSR'd code blocks instead of rebuilding
 * them.
 *
 * Colors are not in the payload: `codeTheme` marks each scope group with a
 * sentinel that maps to a `tk-*` class, and global.css points those at the
 * site's CSS variables. See src/styles/code-theme.ts.
 *
 * Generated *files* rather than Vite virtual modules (this used to be
 * `vite/plugin-snippets.ts`, serving `virtual:snippets`, `virtual:snippet-langs`
 * and `virtual:snippets/<adapter>`) — see update-page-dates.ts's doc comment
 * for why: the per-request SSR handler (src/app-handler.ts) is bundled by
 * Wrangler's own bundler when deployed as a Cloudflare Pages Function, which
 * cannot resolve a Vite virtual module id, but resolves an ordinary file like
 * any other bundler would. `src/lib/framework.ts`'s lazy `import()` per
 * adapter still code-splits exactly as before — it just points at a real file
 * now instead of a virtual module id.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { codeToTokens, type BuiltinLanguage, type ThemeRegistrationRaw } from 'shiki'
import { snippets, type RawSnippet, type HighlightedSnippet, type SnippetToken } from '../src/content/snippets.ts'
import { codeTheme, TOKEN_CLASS } from '../src/styles/code-theme.ts'
import { FRAMEWORKS } from '../src/content/frameworks.ts'
import { frameworkSamples } from './framework-samples.ts'

const OUT_DIR = resolve(import.meta.dirname, '../src/generated/snippets')

type SentinelColor = keyof typeof TOKEN_CLASS

function classFor(color: string | undefined): string {
  if (!color) return ''
  return TOKEN_CLASS[color.toLowerCase() as SentinelColor] ?? ''
}

async function highlightAll(source: Record<string, RawSnippet>): Promise<Record<string, HighlightedSnippet>> {
  const out: Record<string, HighlightedSnippet> = {}

  for (const [name, snippet] of Object.entries(source)) {
    const { tokens } = await codeToTokens(snippet.code, {
      lang: snippet.lang as BuiltinLanguage,
      theme: codeTheme as unknown as ThemeRegistrationRaw,
    })

    out[name] = tokens.map((line) => {
      const merged: SnippetToken[] = []
      for (const token of line) {
        const cls = classFor(token.color)
        // Shiki splits on every scope change; neighbouring runs that land on
        // the same class render identically, so fold them into one span.
        const last = merged[merged.length - 1]
        if (last && last[1] === cls) merged[merged.length - 1] = [last[0] + token.content, cls]
        else merged.push([token.content, cls])
      }
      return merged
    })
  }

  return out
}

async function main(): Promise<void> {
  mkdirSync(OUT_DIR, { recursive: true })

  const baseHighlighted = await highlightAll(snippets)
  const langs = Object.fromEntries(Object.entries(snippets).map(([name, snippet]) => [name, snippet.lang]))

  writeFileSync(
    resolve(OUT_DIR, 'index.ts'),
    `// Generated by scripts/build-snippets.ts — do not edit by hand.\n` +
      `import type { HighlightedSnippet, SnippetLang, SnippetName } from '../../content/snippets.ts'\n\n` +
      `const snippets: Record<SnippetName, HighlightedSnippet> = ${JSON.stringify(baseHighlighted, null, 2)}\n\n` +
      `export const snippetLangs: Record<SnippetName, SnippetLang> = ${JSON.stringify(langs, null, 2)}\n\n` +
      `export default snippets\n`,
    'utf8',
  )
  console.log('[build-snippets] wrote src/generated/snippets/index.ts')

  // Keep in sync with src/lib/home-framework-teaser.ts's DEFAULT_PILL — see
  // that file's comment for why this can't just import the constant.
  const HOME_TEASER_DEFAULT_PILL = 'react'

  for (const framework of FRAMEWORKS) {
    if (framework.id === 'vanilla') continue
    const adapterHighlighted = await highlightAll(frameworkSamples(framework.id))
    writeFileSync(
      resolve(OUT_DIR, `${framework.id}.ts`),
      `// Generated by scripts/build-snippets.ts — do not edit by hand.\n` +
        `import type { HighlightedSnippet, SnippetName } from '../../content/snippets.ts'\n\n` +
        `const snippets: Partial<Record<SnippetName, HighlightedSnippet>> = ${JSON.stringify(adapterHighlighted, null, 2)}\n\n` +
        `export default snippets\n`,
      'utf8',
    )
    console.log(`[build-snippets] wrote src/generated/snippets/${framework.id}.ts`)

    if (framework.id === HOME_TEASER_DEFAULT_PILL) {
      // A dedicated one-snippet file, not just a pointer into `<pill>.ts`:
      // src/pages/overview.ts imports this eagerly (both server and client,
      // so hydration sees the same tree on both sides — see CodeBlock's
      // `initialLines`), and it must stay tiny. The full per-framework files
      // are only ever reached through the lazy `import()` in
      // src/lib/framework.ts's `loaders`, on purpose — bundling one of them
      // into every page load would be exactly the framework-runtime bloat
      // that lazy loading exists to avoid.
      const guide = adapterHighlighted['framework-guide']
      if (!guide) throw new Error(`${HOME_TEASER_DEFAULT_PILL} has no 'framework-guide' sample — src/pages/overview.ts needs one`)
      writeFileSync(
        resolve(OUT_DIR, 'home-teaser-default.ts'),
        `// Generated by scripts/build-snippets.ts — do not edit by hand.\n` +
          `import type { HighlightedSnippet } from '../../content/snippets.ts'\n\n` +
          `const snippet: HighlightedSnippet = ${JSON.stringify(guide, null, 2)}\n\n` +
          `export default snippet\n`,
        'utf8',
      )
      console.log('[build-snippets] wrote src/generated/snippets/home-teaser-default.ts')
    }
  }
}

await main()
