/**
 * Writes `src/generated/package-meta.ts`: the library's version and the real
 * gzipped size of its published ESM bundle.
 *
 * The homepage advertises both, and neither can be measured in a browser — the
 * size comes from gzipping `packages/mother-mask/dist/mother-mask.mjs` at
 * level 9, which needs `node:zlib` and the built artifact on disk. Computing it
 * here means the number is always the current build's, with no string
 * replacement step and nothing to update by hand at release time.
 *
 * A generated *file* rather than a Vite virtual module (this used to be
 * `vite/plugin-package-meta.ts`, serving `virtual:package-meta`) — see
 * update-page-dates.ts's doc comment for why: Wrangler's own bundler, used to
 * deploy src/app-handler.ts as a Cloudflare Pages Function, cannot resolve a
 * Vite virtual module id.
 *
 * Build the library before the docs; the deploy workflow already does.
 */
import { gzipSync } from 'node:zlib'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const PACKAGE_DIR = resolve(import.meta.dirname, '../../packages/mother-mask')
const OUT_FILE = resolve(import.meta.dirname, '../src/generated/package-meta.ts')

interface PackageJson {
  name: string
  version: string
  module: string
}

function measure(): string {
  const pkg = JSON.parse(readFileSync(resolve(PACKAGE_DIR, 'package.json'), 'utf8')) as PackageJson
  const artifact = pkg.module.replace(/^\.\//, '')

  let bundle: Buffer
  try {
    bundle = readFileSync(resolve(PACKAGE_DIR, artifact))
  } catch {
    throw new Error(
      `Cannot measure ${pkg.name}: ${artifact} is missing. Build the library first ` +
        `(cd packages/mother-mask && bun run build).`,
    )
  }

  const bytes = gzipSync(bundle, { level: 9 }).byteLength

  return (
    `// Generated by scripts/update-package-meta.ts — do not edit by hand.\n` +
    `export const packageVersion = ${JSON.stringify(pkg.version)}\n` +
    `export const bundleGzipBytes = ${bytes}\n` +
    `export const bundleGzipSize = ${JSON.stringify(`${(bytes / 1000).toFixed(1)} kB`)}\n` +
    `export const bundleArtifact = ${JSON.stringify(artifact)}\n`
  )
}

mkdirSync(resolve(import.meta.dirname, '../src/generated'), { recursive: true })
writeFileSync(OUT_FILE, measure(), 'utf8')
console.log('[update-package-meta] wrote src/generated/package-meta.ts')
