/**
 * Writes `src/generated/page-dates.ts`: when each page was actually written
 * and last changed, taken from git.
 *
 * This exists because a sitemap that stamps every page with the build date is
 * worse than one with no dates at all — search engines learn that a `lastmod`
 * which changes on every deploy carries no information and stop trusting it.
 * The commit history is the only place that knows which page really changed,
 * so that is where the answer comes from, and a page with no answer gets no
 * `lastmod` rather than a fabricated one.
 *
 * The same dates fill in `datePublished` / `dateModified` on each page's
 * structured data, and the `lastmod` in sitemap.xml (see build-sitemap.ts) —
 * one source for all three.
 *
 * A generated *file* rather than a Vite virtual module (this used to be
 * `vite/plugin-page-dates.ts`, serving `virtual:page-dates`) because the
 * per-request SSR handler (src/app-handler.ts) is bundled by Wrangler's own
 * bundler when deployed as a Cloudflare Pages Function, which has no Vite
 * plugin pipeline to resolve a virtual module id — an ordinary file on disk
 * is resolvable by any bundler. Run by `bun run build` before `vite build`;
 * gitignored like every other generated file.
 *
 * A page's date is its own module's history, not that of the components or
 * stylesheet around it: a change to the shared header is not a change to what
 * the API reference says.
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const PAGES_DIR = resolve(import.meta.dirname, '../src/pages')
const OUT_FILE = resolve(import.meta.dirname, '../src/generated/page-dates.ts')

export interface PageDates {
  /** ISO date of the commit that added the page, or null if it has none yet. */
  created: string | null
  /** ISO date of the last commit to touch it, or null. */
  modified: string | null
}

function git(...args: string[]): string {
  try {
    return execFileSync('git', args, { cwd: PAGES_DIR, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
  } catch {
    return ''
  }
}

function collect(): Record<string, PageDates> {
  const pages = readdirSync(PAGES_DIR)
    .filter((file) => file.endsWith('.ts'))
    .map((file) => file.replace(/\.ts$/, ''))

  const dates: Record<string, PageDates> = {}
  const empty = { created: null, modified: null }

  // A shallow clone only knows about the tip commit, so every file would come
  // back with the same date — exactly the useless signal this module exists to
  // avoid. Say so loudly and emit nothing.
  if (git('rev-parse', '--is-shallow-repository') === 'true') {
    console.warn(
      '[update-page-dates] shallow git clone: no per-page history, so sitemap lastmod and ' +
        'structured-data dates are omitted. Set `fetch-depth: 0` on the checkout step.',
    )
    for (const page of pages) dates[page] = empty
    return dates
  }

  for (const page of pages) {
    const file = `${page}.ts`
    const modified = git('log', '-1', '--format=%cs', '--', file)
    // `--diff-filter=A` finds the commit that added the file; the oldest such
    // commit is its birth, even if it has been deleted and restored since.
    const created = git('log', '--diff-filter=A', '--format=%cs', '--', file).split('\n').filter(Boolean).at(-1)

    dates[page] = modified ? { created: created ?? modified, modified } : empty
  }

  return dates
}

mkdirSync(resolve(import.meta.dirname, '../src/generated'), { recursive: true })
writeFileSync(
  OUT_FILE,
  `// Generated by scripts/update-page-dates.ts — do not edit by hand.\n` +
    `import type { PageDates } from '../../scripts/update-page-dates.ts'\n\n` +
    `const pageDates: Record<string, PageDates> = ${JSON.stringify(collect(), null, 2)}\n\n` +
    `export default pageDates\n`,
  'utf8',
)
console.log('[update-page-dates] wrote src/generated/page-dates.ts')
