import { CodeBlock } from '../components/CodeBlock.ts'
import { SectionHeading } from '../components/SectionHeading.ts'
import { href } from '../router/url.ts'

function row(...cells: NodeModLike<'tr'>[]) {
  return tr(...cells)
}

export function view() {
  return div(
    { className: 'page' },
    section(
      { id: 'patterns' },
      h1({ className: 'page-title' }, 'Pattern syntax'),

      div(
        { className: 'table-wrap' },
        table(
          thead(row(th('Character'), th('Matches'))),
          tbody(
            row(td(code('9')), td('Digit (', code('0'), '–', code('9'), ')')),
            row(td(code('Z')), td('ASCII letter (', code('a'), '–', code('z'), ', ', code('A'), '–', code('Z'), ')')),
            row(td(code('A')), td('ASCII alphanumeric (digit or letter)')),
            row(td('Custom token'), td('Its local matcher and optional transform')),
            row(
              td(code('{n}'), ' / ', code('{min,max}')),
              td('Repeats the token before it — see ', a({ href: '#quantifiers' }, 'bounded quantifiers')),
            ),
            row(td(code('\\')), td('Escapes a token or another backslash')),
            row(td('Anything else'), td('Literal — inserted as the user fills slots')),
          ),
        ),
      ),

      p(
        { style: { marginTop: '12px' } },
        'Array masks: pass patterns ',
        strong('shortest → longest by data capacity'),
        '; the active one is picked from how many data characters are accepted, not a prefix or card network. Use ',
        a({ href: href('advanced-patterns.html') }, code('resolveMask')),
        ' to choose a layout from content instead.',
      ),

      SectionHeading('Bounded quantifiers', 'quantifiers'),
      p(
        'A slot token may be followed by a bounded repeat count. ',
        code('{n}'),
        ' is exactly ',
        em('n'),
        ' occurrences; ',
        code('{min,max}'),
        ' is anywhere from ',
        em('min'),
        ' to ',
        em('max'),
        '.',
      ),
      CodeBlock('patterns-quantifiers'),
      p(
        code('{n}'),
        ' is shorthand — ',
        code('9{4}'),
        ' and ',
        code('9999'),
        ' compile to the same mask. ',
        code('{min,max}'),
        ' adds a ',
        strong('variable-width segment'),
        ', which is what lets a date accept a one- or two-digit day and month without padding:',
      ),
      CodeBlock('patterns-quantifier-bind'),
      p(
        'The separator is how the user picks a width. Typing ',
        code('"3/"'),
        ' commits the one-digit first segment: once a ranged segment reaches its minimum, typing the literal that follows it ends that segment, and the separator stays visible — it is input rather than decoration, so this holds with ',
        code('eager: false'),
        ' too. Typing ',
        code('"12"'),
        ' instead reaches the maximum and may reveal ',
        code('"/"'),
        ' eagerly, exactly as a fixed ',
        code('99'),
        ' segment does. Reaching the minimum alone never inserts anything: after ',
        code('"3"'),
        ' the value is still ',
        code('"3"'),
        ', because the next keystroke could be a second digit.',
      ),
      p(
        strong('Any separator ends the segment, and the mask prints its own.'),
        ' A ranged segment is the one place a mask cannot work out its own boundary, so a person saying "this field is done" gets to say it with whichever divider is under their thumb — a keypad ',
        code('.'),
        ', a ',
        code('-'),
        ', a space — not only the one the pattern happens to spell.',
      ),
      CodeBlock('patterns-quantifier-standin'),
      p(
        "Any Unicode punctuation, symbol, or space works, and each one behaves exactly as the mask's own separator does — same value, same caret. Letters, digits, and other scripts do not: a mistyped ",
        code('"a"'),
        " in a date field is a typo, not a decision, so it stays the noise it always was. Neither does a character this mask's own alphabet accepts — a custom token matching ",
        code('"."'),
        ' makes ',
        code('"."'),
        ' content in that mask, never a boundary. The rule reaches exactly as far as the ambiguity it resolves: a segment only reads a separator this way once it is at or past its minimum and still short of its maximum, so a pattern with no ',
        code('{min,max}'),
        ' segment is completely unaffected — under ',
        code("'99/99/9999'"),
        ', ',
        code('"4."'),
        ' and ',
        code('"4/"'),
        ' alike give ',
        code('"4"'),
        '.',
      ),
      p(
        'Closing a segment early retires the slots it did not use, so a finished value can be shorter than the pattern’s maximum: ',
        code('"3/4/1986"'),
        ' is complete at eight characters even though ',
        code('getMaxLength'),
        ' reports ',
        code('10'),
        '. Anything typed past that point is dropped rather than repacked — the boundaries the user set hold, and the character that no longer fits falls off the end, exactly as an extra digit does on a full fixed mask. ',
        code('maxlength'),
        ' alone is therefore not a completeness check for a ranged mask; inspect the value if you need one.',
      ),
      p(
        'Mother Mask ',
        strong('does not validate dates'),
        ', or anything else semantic — it never inspects a value to decide that ',
        code('"34"'),
        ' cannot be a day and must mean ',
        code('3/4'),
        '. A quantifier is a width rule; explicit separators are how a user says a segment is shorter than its maximum.',
      ),
      p(
        'Only bounded forms are syntax. ',
        code('*'),
        ', ',
        code('+'),
        ', ',
        code('?'),
        ', ',
        code('{n,}'),
        ', ',
        code('{,n}'),
        ', ',
        code('{0}'),
        ' and ',
        code('{2,1}'),
        ' are not, and neither is a repeat count above 1000; those brace sequences stay literal text. A quantifier is only read directly after an unescaped token, so ',
        code("'\\9{1,2}'"),
        ' is the literal text ',
        code('9{1,2}'),
        '. ',
        a({ href: href('api.html') }, code('getMaxLength')),
        ' and the ',
        code('maxlength'),
        ' ',
        code('bind'),
        ' sets use the compiled maximum (',
        code('10'),
        ' for ',
        code("'9{1,2}/9{1,2}/9{4}'"),
        '), never the length of the pattern source, and array masks still select by compiled slot capacity.',
      ),

      SectionHeading('Escaped literals'),
      CodeBlock('patterns-escapes'),
      p(
        'Backslash escapes a built-in or custom token, or another backslash. Before any other character, or at the end of a pattern, it remains literal. JavaScript string literals need an extra backslash as shown above. Older patterns using backslash immediately before a token must double it to keep the backslash in the output.',
      ),
      p(
        'Complete literal runs are formatting at their boundaries; escaped runs remain formatting after a segment shrinks. If a literal also matches the data alphabet, raw and formatted values can be ambiguous. Use a distinct separator, such as ',
        code("'\\9-99'"),
        ', and avoid resolver literals that look like data but are absent from the fallback pattern.',
      ),
    ),
  )
}
